Template.help.helpers
  title: ->
    RocketChat.settings.get 'Layout_Home_Title'
  body: ->
    RocketChat.settings.get 'Layout_Home_Body'
  userId: ->
    Meteor.userId()
  currentUser: ->
    x = undefined
    x = RocketChat.models.Users.findOne('_id': Meteor.userId())
    x
  networkCount: ->
    q = undefined
    x = undefined
    x = RocketChat.models.Users.find({}).fetch()
    q = x.length
    q
Template.help.events 'submit .form-horizontal': (event) ->
  category = undefined
  data = undefined
  offer = undefined
  errorSituation = undefined
  selfUserId = undefined
  situation = undefined
  target = undefined
  url = undefined
  userName = undefined
  event.preventDefault()
  target = event.target
  category = target.category.value
  userName = target.userName.value
  situation = target.situation.value
  offer = target.os0.value
  selfUserId = Meteor.userId()
  data =
    category: category
    situation: situation
    userName: userName
    offer: offer
    selfUserId: selfUserId
  if !situation || target.situation.value == '!!!! PLEASE DESCRIBE YOUR SITUATION !!!!'
    url = '/help'
    target.situation.value = '!!!! PLEASE DESCRIBE YOUR SITUATION !!!!'
    return FlowRouter.go(url)
  console.log data
  Meteor.call 'addCustomFields', data, ->
  return
# ---
# generated by coffee-script 1.9.2

# ---
# generated by js2coffee 2.2.0
